main: com.buffsovernexus.Authority
name: Authority
version: '1.0'
description: Handles a Minecraft server's basic authoritative interactions.
author: BuffsOverNexus
website: buffsovernexus.com/authority

commands:
  authority:
    description: Handles all authority-related commands
  ahome:
    description: Teleport to a saved home
  shome:
    description: Create or update a home
  dhome:
    description: Delete a home
  ahomes:
    description: View all saved homes
  cclear:
    description: Clear chat history